//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNHBUSService.ResDAOWS {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResDAOWS.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadListOfRes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet LoadListOfRes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadListOfRes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> LoadListOfResAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Insert(QLNHBUSService.ResDAOWS.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertAsync(QLNHBUSService.ResDAOWS.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Delete(int ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DeleteAsync(int ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update(QLNHBUSService.ResDAOWS.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateAsync(QLNHBUSService.ResDAOWS.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadListOfCato", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet LoadListOfCato();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadListOfCato", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> LoadListOfCatoAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Restaurant : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ipField;
        
        private string nameField;
        
        private string addressField;
        
        private string describeField;
        
        private int categoryIPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
                this.RaisePropertyChanged("IP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Describe {
            get {
                return this.describeField;
            }
            set {
                this.describeField = value;
                this.RaisePropertyChanged("Describe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int CategoryIP {
            get {
                return this.categoryIPField;
            }
            set {
                this.categoryIPField = value;
                this.RaisePropertyChanged("CategoryIP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : QLNHBUSService.ResDAOWS.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<QLNHBUSService.ResDAOWS.WebService1Soap>, QLNHBUSService.ResDAOWS.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet LoadListOfRes() {
            return base.Channel.LoadListOfRes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LoadListOfResAsync() {
            return base.Channel.LoadListOfResAsync();
        }
        
        public int Insert(QLNHBUSService.ResDAOWS.Restaurant restaurant) {
            return base.Channel.Insert(restaurant);
        }
        
        public System.Threading.Tasks.Task<int> InsertAsync(QLNHBUSService.ResDAOWS.Restaurant restaurant) {
            return base.Channel.InsertAsync(restaurant);
        }
        
        public int Delete(int ip) {
            return base.Channel.Delete(ip);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(int ip) {
            return base.Channel.DeleteAsync(ip);
        }
        
        public int Update(QLNHBUSService.ResDAOWS.Restaurant restaurant) {
            return base.Channel.Update(restaurant);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(QLNHBUSService.ResDAOWS.Restaurant restaurant) {
            return base.Channel.UpdateAsync(restaurant);
        }
        
        public System.Data.DataSet LoadListOfCato() {
            return base.Channel.LoadListOfCato();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> LoadListOfCatoAsync() {
            return base.Channel.LoadListOfCatoAsync();
        }
    }
}
